version: '3'

services:
  database:
    container_name: mywebdns_mysql
    image: 'mysql:5.7.40'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306:3306'
    volumes:
      - ./docker_volumes/db/data:/var/lib/mysql:rw
